name: 'Revolution Medicine '
favicon: null
layout_spectrum: 0.36252961214631796
typography_spectrum: 0.5686146076768637
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0e0e0e'
    - '#bdb3aa'
    - '#ffffff'
    - '#676767'
    - '#ffa150'
  brandStrength: 0.5
  lightness: 0.953223887598142
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
