name: 'Revolution Medicine '
favicon: null
layout_spectrum: 0.36252961214631796
typography_spectrum: 0.5686146076768637
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f8f8f6'
    - '#4f9de8'
    - '#0070d2'
    - '#775047'
    - '#223212'
  brandStrength: 0.25
  lightness: 0.953223887598142
  saturation: 0.25
  rhythmicContrast: 0.5
purpose: []
