name: 'Revolution Medicine '
favicon: null
layout_spectrum: 0.36252961214631796
typography_spectrum: 0.5686146076768637
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.19311897759325802
  lightness: 0.953223887598142
  saturation: 0.17990187276154757
  rhythmicContrast: 0.5990094018634409
purpose: []
